Document return types of parse() and validate()
w3c/webidl2.js pull request #582
Opened 2021-04-26 16:16 UTC by foolip

2021-04-26 16:17 UTC, foolip commented
I don't really know what I'm doing here. I think this is correct, but I don't know how things would fail if it were wrong.

2021-05-10 22:37 UTC, saschanaz requested changes

2021-05-10 22:37 UTC, saschanaz commented on lib/validator.js
> + * @return {error[]} validation errors
`*[]` is better than `*` but `error[]` is not since there is no type named `error`. Maybe also `*[]` for now?

2021-08-18 11:59 UTC, saschanaz approved these changes
Adjusted a bit myself, merging.

2021-08-18 11:59 UTC, merged